  set(CMAKE_SYSTEM_NAME Linux)
  set(CMAKE_SYSTEM_PROCESSOR aarch64)

  set(CMAKE_SYSROOT "/home/ryan/sysroots/rpi5-bookworm-arm64")

  set(CMAKE_C_COMPILER aarch64-linux-gnu-gcc)
  set(CMAKE_CXX_COMPILER aarch64-linux-gnu-g++)

  set(CMAKE_C_FLAGS_INIT "--sysroot=${CMAKE_SYSROOT}")
  set(CMAKE_CXX_FLAGS_INIT "--sysroot=${CMAKE_SYSROOT}")
  set(CMAKE_SHARED_LINKER_FLAGS_INIT "--sysroot=${CMAKE_SYSROOT}")

  set(CMAKE_FIND_ROOT_PATH "${CMAKE_SYSROOT}")

  set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
  set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
  set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
  set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
